app = "tcl"  # Thay bằng tên ứng dụng của bạn, ví dụ: "telegram-bot-123"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/python"

[env]
  PORT = "8080"  # Không cần thiết cho bot Telegram, nhưng Fly yêu cầu

[processes]
  app = "python bot.py"  # Lệnh chạy bot